### ISSUE TITLE
Error: eval js error: TypeError

### ISSUE THREAD

**Issue by sinawic** [koki-develop/clive#80]
Hi there

I have downloaded this version of the clive
https://github.com/koki-develop/clive/releases/tag/v0.12.4
clive_Linux_x86_64.tar.gz

and I've got the ttyd package installed.
I've run `./clive init` and created the default `clive.yml` file.
with the default config when I run `./clive start` I get the following error:

```
Error: eval js error: TypeError: Cannot set properties of undefined (setting 'fontSize')
    at <anonymous>:1:51
    at <anonymous>:1:57 <nil>
```

also when I run `./clive validate` I get the following:
Config file clive.yml is valid!

here's my `uname -a` result:
Linux devops 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sinawic** [comment]
a chrome window starts and closes immediately!

**Comment by koki-develop** [comment]
@sinawic 
Thank you for opening an issue!
Could you please tell me the result of running the following command?

```
ttyd --version
```

**Comment by koki-develop** [comment]
@sinawic 
Thank you!
It appears that this problem may occur if the version of ttyd is less than 1.7.0.
Could you please try again after upgrading ttyd to version 1.7.0 or higher?

**Comment by sinawic** [comment]
I installed the ttyd package using apt 
and it seems the version you mentioned does not exist on the package manager.
do you think I should install it from the source or?

**Comment by koki-develop** [comment]
@sinawic 
Yes, that could be a good idea, or you might want to directly download the binary from the [Releases](https://github.com/tsl0922/ttyd/releases) page.
For instance, like this:

```
$ wget 'https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64'
$ chmod +x ./ttyd.x86_64
$ mv ./ttyd.x86_64 /usr/local/bin/ttyd
$ ttyd --version
```

**Comment by sinawic** [comment]
thank you so much. the problem seems to be solved now with ttyd version 1.7.3

I guess it's better mentioning it on the docs!
if you want I can make a pr tho

**Comment by koki-develop** [comment]
@sinawic 
> the problem seems to be solved now with ttyd version 1.7.3

I'm glad to hear that. 👍 
Thank you for checking and letting us know!!
I was able to identify this problem thanks to your report!!

> also I wanted a feature for the ttyd to exit after the execution is finished.

cLive should automatically terminate the ttyd process upon exit, isn't it working properly?
Even executing `exit` won't terminate the ttyd process (this is a specification of ttyd).

**Comment by sinawic** [comment]
uh I'm sorry
this is not at all a bug

by passing `skipPauseBeforeQuit: true` I get my expected result

I read the docs but didn't understand it meant the same thing I wanted.

thanks for the response :pray:

**Comment by koki-develop** [comment]
Ah, I see, is that so!
I'm really glad I could help with solving the problem!
If there's anything else, feel free to open another issue! 👍
